### ISSUE TITLE
Hotbar Highlight is inverted

### ISSUE THREAD

**Issue by deannreid** [DayZ-n-Chill/Colorful-HUD#6]
![image](https://user-images.githubusercontent.com/5481657/229367545-23c8ca76-b0ff-4fe2-8ad3-733e8d877622.png)

The HK is on Slot 1 but the light colour is inverted

**Comment by DrkDevil** [comment]
No that is correct.  the one that is in your hands is #1 This is actually how dayz does it naturally.  if you have like 6 items in your inventory slots you will see.  I do agree the experience could be better though. But this is how dayz does it. It is using a disabled color state on items you don't have in your hands natively.  We can convert this to an task.

**Comment by deannreid** [comment]
Ah - Never even noticed that before on the old UI
